Super-Sweet-Starbursts/agenda

package-lock.json, package.json, script/seed.js, script/taskSeed.js, server/db/models/index.js, server/db/models/task.js
*** NEW DEPENDENCY INSTALLED, PLEASE NPM INSTALL ***
* wrote task model
* wrote task seed file
=> task model and seed file created

client/components/navbar.js, public/index.html, script/seed-data/index.js, script/seed-data/user-seeds.js, script/seed.js, server/db/models/user.js
=> feat: added user model

script/checklistItemData.js, script/mantraData.js, server/db/models/checklistItem.js, server/db/models/index.js, server/db/models/mantra.js
=> Feat: Created DB models and seed file for Mantras and CheckListItems

script/seed-data/checklist-item-seed.js, script/seed-data/index.js, script/seed-data/mantra-seed.js, script/seed.js, server/db/models/checklist-item.js, server/db/models/index.js
Cleaned up mantra and checklist items database files
=> Chore: cleaned up mantra and checklist DB files

script/seed-data/association-seed.js, script/seed-data/index.js, script/seed-data/user-seed.js, script/seed.js, server/db/models/checklist-item.js
=> feat: added association seeds

script/seed-data/board-seed.js, script/seed-data/checklist-item-seed.js, script/seed-data/task-seed.js
* added board/user, checklist/user, and board/task
=> added more comprehensive seed associations

server/api/checklist-items.js, server/api/index.js
=> Feat: Added Express routes for personal checklist

client/components/UserHome.js, client/store/index.js, client/store/mantras.js, server/api/boards.js
* fixed all boards route to be functional
* all boards route now gets mantras from db
* userhome component NOT functional
=> fixed all boards route, added mantra store

client/index.js, client/socket.js, server/index.js, server/socket/index.js
* got rid of all socket-related items
=> got rid of socket stuff

client/components/List.js, client/components/SingleBoard.js
SingleBoard with Tasks is now on the state when it gets to `http://localhost:8080/boards/${boardId}`
=> ac/import List to SingleBoard

client/components/AuthForm.js, client/components/UserHome.js, server/auth/index.js
=> fix: fixed bug on signup form-field validation

client/components/List.js, client/components/SingleBoard.js, client/store/all-tasks.js, client/store/index.js, client/store/tasks.js, public/style.css, server/api/tasks.js
=> AC/ add gradient background

client/components/UserHome.js, client/store/all-boards.js, client/store/mantras.js, server/api/boards.js
* also added comments for clarity!!
=> randomized mantra and board names now appear on user home

server/db/models/index.js
=> fix: fixed the file name on db/models

client/components/Task.js, client/store/tasks.js, server/api/tasks.js
* tasks can be edited
* move around within a board based on type
* api routes reorganized
=> tasks are now fully editable and can be moved within a board

client/store/tasks.js, server/api/tasks.js
=> Feat: Route and thunk for users to be assigned to tasks

server/db/db.js
=> fix: added a condition on database_url

client/components/AddUserToTask.js, client/components/SingleBoard.js, client/components/Task.js, server/api/tasks.js
=> Feat: react component to render add users to task button

client/routes.js
=> swapped routes

server/api/boards.js, server/api/routerMiddleware.js, server/api/tasks.js
=> Refactor router middleware

client/components/Checklist.js, client/components/UserHomeMUI.js
=> fix(user home) resize boxes in home view

client/components/CustomMUI/UserHomeMUI.js, client/components/UserHome.js, client/theme/theme.js
* restored font
* responsive text
* font still small on buttons...
=> style(userhome): restore responsive font

client/components/CustomMUI/SingleBoardMUI.js, client/components/CustomMUI/UserHomeMUI.js, client/components/SingleBoard.js, client/components/UserHome.js, client/store/single-board.js
* refactored single board component to be functional instead of class
* delete single board
* modal pops up to confirm deletion
=> feat, refactor(singleboard): delete single board

client/components/AddUserToTask.js, client/components/UserAvatar.js, client/store/tasks.js, server/api/routerMiddleware.js, server/api/tasks.js
=> feat(component): added unassign-user-from-task button

client/components/CustomMUI/UserHomeMUI.js, client/components/UserHome.js
=> refactor Single Board Buttons

client/components/AuthForm.js, client/routes.js
=> Feat(component): Add styling to login/sign up component

client/components/Checklist.js, client/components/CustomMUI/NavBarMUI.js, client/components/CustomMUI/UserHomeMUI.js, client/components/UserHome.js, client/components/navbar.js, client/theme/theme.js, public/index.html
-separated Material UI from Navbar component
-still working on the UI
=> Fix(Navbar) - Refactor Material UI Component

client/components/List.js, client/components/SingleBoard.js, client/components/Task.js, package-lock.json, package.json
=> feat(task): draggable tasks, not droppable yet

client/components/AddUserToBoard.js, client/routes.js
=> fix(Routes): added login route for home path

client/components/List.js
* fixed list widths!! (for real this time)
=> style(lists): fixed list widths

client/components/List.js
* fixed list heights so they're responsive to the amount of tasks
=> style(task): quick style fix for list height

client/components/SingleBoard.js, client/store/all-tasks.js, client/store/tasks.js
* fixed the drag and drop flicker for individual tasks
=> bugfix(tasks): drag and drop flicker eliminated

README.md
=> update README to include collaborators

client/components/List.js, client/components/SingleBoard.js, client/components/Task.js
What I did:
- Removed assign user to task option in tasks inside of personal boards
=> Feat(task): Remove assign tasks option in tasks from personal boards

client/components/CustomMUI/FooterMUI.js, client/components/CustomMUI/ToggleButtonMUI.js, client/components/Footer.js, client/components/ThemeToggle.js
=> Add (ToggleButtons) to footer nav for theme toggle, currently not functional

client/components/AddUserToBoard.js, client/components/AddUserToTask.js, client/components/CreateBoard.js, client/components/DeleteTask.js, client/components/List.js, client/components/SingleBoard.js, client/components/Task.js, client/components/TaskForm.js, client/components/ThemeToggle.js, client/components/UserAvatar.js
=> refactor(all) remove all aria tags

client/components/AddUserToBoard.js, client/components/Chips.js
=> fix(Chip): changed it to blank chips

client/components/Checklist.js, client/components/CustomMUI/ChecklistMUI.js, client/components/CustomMUI/GradientButton.js, client/components/CustomMUI/UserHomeMUI.js, client/components/Footer.js, client/components/UserHome.js, client/theme/theme.js
=> Enhance (User Home) grid spacing

client/index.js, client/socket.js, client/store/all-tasks.js, server/index.js, server/socket/index.js
=> Feat: Add back sockets into app

client/app.js, client/components/CustomMUI/CustomThemeProvider.js, client/components/DeleteTask.js, client/components/List.js, client/components/Task.js, client/components/ThemeToggle.js, client/components/UserHome.js, client/theme/darkTheme.js
=> Fix(UI) create CustomThemeProvider for theme toggle

client/socket.js, client/store/all-tasks.js, client/store/single-board.js, client/store/tasks.js, server/socket/index.js
What I did:
Worked with Ako to implement sockets for shared boards
=> Feat: Added working sockets for shared boards

client/app.js, client/components/Footer.js, client/components/ThemeToggle.js, client/components/index.js, client/theme/baseTheme.js, client/theme/components/CustomThemeProvider.js, client/theme/index.js, client/theme/normalTheme.js, client/theme/wildcardTheme.js
=> feature(toggle theme) enable button functionality to toggle theme

client/components/Footer.js, client/components/ThemeToggle.js, client/theme/baseTheme.js, client/theme/components/CustomThemeProvider.js, client/theme/index.js, client/theme/starTheme.js
=> Fix[Toggle Theme] ThemeProvider props error

client/components/CustomMUI/TaskMUI.js, client/components/Task.js, client/components/TaskForm.js, client/functions.js
* date color changes without refresh
* date picker calender closes when a date is selected
=> feat(dueDate): due date closes on select, title color changes

script/seed-data/association-seed.js
What I did:
Forgot to adjust the new label names in our seed file
=> Fix: Updated label name in association seed file

client/components/CustomMUI/SingleBoardMUI.js, client/components/SingleBoard.js
=> Fix[Single Board] swap out delete button for theme button

client/components/CustomMUI/TaskMUI.js, client/components/DeleteTask.js, client/components/List.js, client/components/Task.js, client/functions.js
* changed due date to highlight red when due/past due
* removed autofill from task forms
=> style(dueDate): changed due date styling

client/components/Checklist.js, client/components/CustomMUI/ChecklistMUI.js, client/components/CustomMUI/FooterMUI.js, client/components/CustomMUI/GradientAccordion.js, client/components/CustomMUI/GradientButton.js, client/components/CustomMUI/NavBarMUI.js, client/components/CustomMUI/UserHomeMUI.js, client/components/CustomMUI/listMUI.js, client/components/Footer.js, client/components/List.js, client/components/SingleBoard.js, client/components/UserHome.js, client/components/navbar.js, client/theme/darkTheme.js, client/theme/normalTheme.js, client/theme/starTheme.js, client/theme/wildcardTheme.js
=> Fix[Toggle Themes] colors toggle to legible color scheme

client/components/List.js
=> Fix: Double accordion bug

client/components/CustomMUI/SingleBoardMUI.js, client/components/CustomMUI/listMUI.js, client/components/List.js, client/components/SingleBoard.js
=> style: single board & list titles made consistent

client/components/List.js
=> fixed error

server/auth/google.js
=> fix: heroku google

client/components/CustomMUI/TaskMUI.js, client/components/Task.js
* tasks now render the same every time
=> bug: task accordion style stays consistent

client/components/AddUserToBoard.js, client/components/DeleteUserFromBoardDialog.js, client/components/SingleBoard.js
=> fix: fixed a bug on user deleting another user

client/socket.js, client/store/all-tasks.js, server/socket/index.js
=> Fix:remove all tasks socket

.travis.yml, package-lock.json, package.json
=> added api key

client/socket.js, server/socket/index.js
=> chore: add notes

.travis.yml
=> commented out test on travis

client/components/AddUserToBoard.js, client/components/Checklist.js, client/components/CustomMUI/FooterMUI.js, client/components/CustomMUI/GradientButton.js, client/components/CustomMUI/UserHomeMUI.js, client/components/UserHome.js, client/store/single-board.js, client/theme/darkTheme.js, client/theme/normalTheme.js
* buttons match the theme
* higher contrast fonts and icons
* dark theme made darker
* add user to board now displays error message on page instead of navigating away
* board names on all board view respond to capitalization
=> style, bugfix(themes, addtask): higher theme contrasts, add user displays error without leaving the page
